# Example configuration file
infoblox:
  -
    master: infoblox.master.com
    wapi_version: 2.10.5
    username: foo
    password: bar
    discovery:
      # members include discovery of members, nodes and dns_servers
      - members
      # discover infoblox zones
      - zones
      # discover dhcp ranges that are not excluded in section exclude_ranges
      - dhcp_ranges
      # discover web endpoints from the networks defined in
      - web_endpoints


    # the exclusion_label is removed and replaced with the exclusion_labels defined below

    # Exclusion labels match labels in extattrs in infoblox and if the label value string is "True" or "true"
    # it will be excluded.- discovery:
    # Labels can be defined as common for all types or specific for each object type
    exclusion_labels:
      commons:
        - common-exclusion
      members:
        - member-exclusion
      dhcp_ranges:
        - dhcp-exclusion
      zones:
        # for zones that are "disabled" in Infoblox are by default excluded
        - zone-exclusion

    # Networks subject to detect web endpoints
    web_endpoints:
      networks:
        - 192.91.218.0/24

    # Infoblox dhcp range prefix to exclude
    exclude_ranges:
      # A.B.C.0/29
      - 29
      - 30
